<?php
    //modifica estos valores para personalizar la plantilla
    //Modificalos segun esté en el formulario o info que te proporcionen
    $nombre_contacto = "nombre";
    $telefono_contacto = "5500000000";
    $dominio = "yamblet.com";
    $correo = "correo@ejemplo.com";
    $titulo = "titulo";
    $propuesta_valor_corta = "propuesta de valor corta";

    //puedes añadir los colores por nombre o por hexadecimal
    $tema_color_1 = "black";
    $tema_color_2 = "white";
    $tema_color_3 = "#EAEFEF";
    $tema_color_4 = "#111877"; //este color es el que aparecerá en la barra de navegacion de chrome para a movil
    //si necesitas mas colores añadelo aqui y hazle echo en el documento 
    $descripcion_negocio = "descripcion negocio";
    $decripcion_negocio_slogan = "descripcion con slogan (lo que aparezca en el formulario)";

    //púedes añadir texto adicional con una variable o directamente al documento, como prefieras (siempre con buena ortografia, no como el desarrollador que hizo esta plantilla) 
    $texto= "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ultrices viverra lectus, vel volutpat velit sodales nec. Aenean lacinia nunc diam, vitae iaculis metus tincidunt ut. Integer efficitur dui et mauris tempus, a maximus enim suscipit. Pellentesque aliquet gravida justo, ut vestibulum magna molestie et. Nunc non auctor nulla. Vivamus pulvinar libero ut rhoncus molestie. Nam sed egestas arcu, eu condimentum diam. Maecenas tristique facilisis egestas. Aenean eget metus elit. Quisque aliquet, enim vel efficitur faucibus, justo mi rutrum nunc, eget pretium orci est in mauris. Donec a pulvinar tortor, ut sagittis nulla. Nam posuere varius arcu a aliquet. Nunc vitae velit urna. Aliquam molestie, metus non congue consectetur, tellus orci iaculis lacus, ut luctus mi ex eget nulla. Aenean sollicitudin ipsum quam, a cursus est pellentesque sit amet.";
    $telefono = 5511223344; //telefono local
    $telefono_wa = 5511223344; //numero que lanza el icono de whatsapp
    $ubicacion = "direccion completa del contacto";
    $link_contacto = "google.com";//link a otra web si lo requiere
    $correo_contacto = "correo@correocorporativo.com"; //como aparezca en el formulario, se creará despues de que se compre el dominio
    $mensaje_default_WA="Hola"; //el mensaje con el que se va alanzar el boton de whatsapp

    //si no tiene alguna de las redes borra el icono en la parte del footer que dice "redes sociales"
    $instagram="instagram";
    $facebook="facebook";
    $twitter="twitter";
    //en caso de faltar alguna (linkedin o youtube) añadela en el footer con su icono de font awesome correspondiente
    
    //remplaza las imagenes que necesites (o como se vea mejor)
    $icono = "images/azul-rojo.png"; //imagen que aparece en la pestaña del navegador
    $header = "images/header-03.jpg"; //imagen de fondo en la seccion header
    $imagen_perfil = "images/azul-rojo.png"; //imagen central en la seccion header
    $footer = "images/azul.png"; //imagen que aparece en el footer
    $navbar = "images/azul.png"; //imagen que aparece en el brand del navbar

    //cuando entregues, borra todos los comentarios de ayuda del documento :u
?>
    <!DOCTYPE html>
    <html lang="es">

    <head>
        <!-- Open Graph Meta Tags generated by MashShare 3.7.5 - https://mashshare.net -->
        <meta property="og:type" content="website" />
        <meta property="og:title" content="<?php echo $titulo ?>" />
        <meta property="og:description" content="<?php echo $titulo.' | '.$propuesta_valor_corta?>" />
        <meta property="og:image" content="<?php echo $icono ?>" />
        <meta property="og:url" content="<?php echo $dominio ?>" />
        <meta property="og:site_name" content="<?php echo $titulo ?>" />
        <meta property="og:updated_time" content="2020-04-09T18:49:34-04:00" />

        <!-- This site is optimized with the Yoast SEO plugin v14.0.4 - https://yoast.com/wordpress/plugins/seo/ -->
        <title><?php echo $titulo ?> | Sitio Oficial</title>
        <meta name="description" content="<?php echo $descripcion_negocio ?>" />
        <meta name="robots" content="index, follow" />
        <meta name="googlebot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
        <meta name="bingbot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
        <link rel="canonical" href="<?php echo $dominio ?>" />
        <link rel="icon" type="image/x-icon" href="<?php echo $icono ?>">
        <meta property="og:locale" content="es_ES" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="<?php echo $titulo ?>" />
        <meta property="og:description" content="<?php echo $descripcion_negocio ?>" />
        <meta property="og:url" content="<?php echo $dominio ?>" />
        <meta property="og:site_name" content="<?php echo $titulo ?>" />
        <meta property="article:publisher" content="<?php echo $dominio ?>" />
        <meta property="article:author" content="<?php echo $nombre_contacto ?>" />
        <meta property="og:image" content="<?php echo $icono ?>" />
        <meta property="og:image:width" content="330" />
        <meta property="og:image:height" content="330" />
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Sintony:wght@400;700&display=swap" rel="stylesheet">
        <script src='https://kit.fontawesome.com/a076d05399.js'></script>
        <meta name="msapplication-TileColor" content="<?php echo $tema_color_1 ?>">
        <meta name="msapplication-TileImage" content="<?php echo $icono ?>">
        <meta name="theme-color" content="<?php echo $tema_color_4?>">
        
        <!--si necesitas añadir mas estilo hazlo aquí-->
        <!--elimina los estilos que no necesitas-->
        <style>
            body {
                font-family: 'Raleway', sans-serif;
                background-color: <?php echo $tema_color_2?>;
            }
            
            .container-fluid {
                padding: 0!important;
            }
            
            .navbar {
                padding: 1rem;
                background-color: <?php echo $tema_color_4 ?>!important;
            }
            
            h4 {
                font-weight: 300;
            }
            
            .jumbotron {
                padding: 6rem 2rem;
                border-radius: 0rem;
            }
            
            img {
                box-shadow: 1px 1px 10px 3px #00000042;
            }

            h2, h3, h4,li {
                color: <?php echo $tema_color_4 ?>;
                font-family: 'Raleway', sans-serif;
                font-weight: 700;
            }
            h1 {
                color: <?php echo $tema_color_4 ?>;
                font-family: 'Raleway', sans-serif;
                font-weight: 700;
            }
            label, p, a {
                color: <?php echo $tema_color_1 ?>;
                font-family: 'Raleway', sans-serif;
            }
            .btn {
                background-color: <?php echo $tema_color_4 ?>;
                color: <?php echo $tema_color_2 ?>;
            }
            .container-fluid {
                color: <?php echo $tema_color_1 ?>;
            }
            footer{
                color: <?php echo $tema_color_1?>;
                background-color: <?php echo $tema_color_2?>;
            }
            .col{
                text-align: justify;
            }
            i{
                color: <?php echo $tema_color_4 ?>; 
            }
            .footer{
                background-color:<?php echo $tema_color_3?>;
            }
        </style>
    </head>

    <body id="page-top">
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v9.0" nonce="FOEVmYye"></script>
        <!--NAVBAR-->
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark"><!--si el color de la navbar es claro, cambia a navbar-light-->
            <a class="navbar-brand" href="#page-top"><img class="img-responsive" src="<?php echo $navbar?>" style="box-shadow:none; height: 2rem;"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!--añade los items que necesites-->
                
                <li class="nav-item">
                    <a class="nav-link " href="#seccion1">Primer sección</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="#seccion2">Segunda sección</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="#seccion3">Tercera sección</a>
                </li>
            </ul>
            </div>
        </nav>
        <!--añade las secciones que necesites-->

        <!--HEADER-->
        <div class="container-fluid" >
            <!--cambia el text-align para mover la imagen de perfil, el titulo y la descripcion del negocio, ya sea a la izquierda, al centro o a la derecha-->
            <div class="jumbotron" style="text-align: left; background-image: url(<?php echo $header ?>);background-repeat: no-repeat;background-attachment: scroll;background-position: center center;background-size: auto;">
                <img src="<?php echo $imagen_perfil ?>" style="box-shadow: none;max-height:220px; border-radius: 50%;" class="img-fluid">
                <h1><?php echo $titulo ?></h1>
                <h4><?php echo $descripcion_negocio ?> </h4>
            <br><br>
            </div>
        </div>
        <!--seccion 1-->
        <div class="container" id="seccion1">
            <div class="row">
                <div class="col-12" style="padding: 2rem"  >
                    <h1 style="text-align: center; padding: 2rem;">
                        Nosotros
                    </h1>
                    <p class="p-4">
                    <?php echo $decripcion_negocio_slogan ?>
                    </p>
                </div>
            </div>
        </div>
        <!--seccion 2-->
        <div class="container" id="seccion2">
            <div class="row">
            <div class="col-12" style="padding: 2rem"  >
                    <h1 style="text-align: center; padding: 2rem;">
                        Servicios
                    </h1>
                    <p class="p-4"><?php echo $texto?></p>
                </div>
            </div>
        </div>
        <!--seccion 3-->
        <div class="container" id="seccion3">
            <div class="row">
                <div class="col-12" style="padding: 2rem"  >
                    <h1 style="text-align: center; padding: 2rem;">
                        Mercados
                    </h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ultrices viverra lectus, vel volutpat velit sodales nec. Aenean lacinia nunc diam, vitae iaculis metus tincidunt ut. Integer efficitur dui et mauris tempus, a maximus enim suscipit. Pellentesque aliquet gravida justo, ut vestibulum magna molestie et. Nunc non auctor nulla. Vivamus pulvinar libero ut rhoncus molestie. Nam sed egestas arcu, eu condimentum diam. Maecenas tristique facilisis egestas. Aenean eget metus elit. Quisque aliquet, enim vel efficitur faucibus, justo mi rutrum nunc, eget pretium orci est in mauris. Donec a pulvinar tortor, ut sagittis nulla. Nam posuere varius arcu a aliquet. Nunc vitae velit urna. Aliquam molestie, metus non congue consectetur, tellus orci iaculis lacus, ut luctus mi ex eget nulla. Aenean sollicitudin ipsum quam, a cursus est pellentesque sit amet.</p>
                </div>
            </div>
        </div>
        <!--footer-->
        <div class="footer container-fluid" id="contacto" style="text-align: center">
            <div class="row justify-content-center" style="margin: 0; padding: 2rem; text-align: center">
                <div class="col" style="padding: 2rem; text-align: center">
                    <br> <img src="<?php echo $footer ?>" class="img-fluid" style="max-width:220px; box-shadow: none;">
                    <br>
                    <br>
                    <!--h4 style="color: font-weight: 100"><?php echo $titulo ?></h4-->
                </div>
                <div class="" style="padding: 2rem; text-align: center">
                    <br>
                    <h3 >
                        Contacto
                    </h3>
                    <p class=""  style="font-weight: 400">
                        <!--borra los que no necesites-->
                        <a href="mailto: <?php echo $correo ?>"><?php echo $correo ?></a> <br>
                        <a href="mailto:<?php echo $correo_contacto ?>"><?php echo $correo_contacto ?> </a> <br>
                        <a href="<?php echo $link_contacto ?>"><?php echo $nombre_contacto ?> </a> <br>
                        <a href="tel:<?php echo $telefono ?>"><?php echo $telefono ?> </a> <br>
                    </p>
                </div>
                <div class="col" style="padding: 2rem; text-align: center">
                    <br>
                    <h3>
                        Redes Sociales
                    </h3>
                    <p>
                        <!--iconos de fontawesome para redes sociales con sus links. Borra los que no uses-->
                        <a href="https://api.whatsapp.com/send?phone=<?php echo $telefono_wa?>&text=<?php echo $mensaje_default_WA?>" target="_blank"><i class='fab fa-whatsapp' style='font-size:28px; padding: 1rem'></i></a>
                        <a href="https://instagram.com/<?php echo $instagram ?>" target="_blank"><i class="fab fa-instagram" style="font-size:28px; padding: 1rem"></i></a>
                        <a href="https://twitter.com/<?php echo $twitter ?>" target="_blank"><i class='fab fa-twitter' style='font-size:28px; padding: 1rem'></i></a>
                        <a href="https://facebook.com/<?php echo $facebook ?>" target="_blank"><i class='fab fa-facebook' style='font-size:28px; padding: 1rem'></i></a>
                    </p>
                </div>
            </div>
        </div>
    </body>
    </html>